/**
 * MaxwinServiceApi
 * Cluttery Maxwin game client API
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

(function(root, factory) {
  module.exports = factory(require('../ApiClient'), require('../model/Game'), require('../model/Error'));
}(this, function(ApiClient, Game, Error) {
  'use strict';

  /**
   * Games service.
   * @module api/GamesApi
   * @version 1.0.0
   */

  /**
   * Constructs a new GamesApi. 
   * @alias module:api/GamesApi
   * @class
   * @param {module:ApiClient} apiClient Optional API client implementation to use,
   * default to {@link module:ApiClient#instance} if unspecified.
   */
  var exports = function(apiClient) {
    this.apiClient = apiClient || ApiClient.instance;


    /**
     * Callback function to receive the result of the gamesGetCurrentGames operation.
     * @callback module:api/GamesApi~gamesGetCurrentGamesCallback
     * @param {String} error Error message, if any.
     * @param {Array.<module:model/Game>} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Returns current games info
     * Returns following info about current running games: 1. game address 2. finished flag 3. maxAmount maximum bet 4. balance amount of money in the bank 5. timeToFinish msecs to game fininsh 
     * @param {module:api/GamesApi~gamesGetCurrentGamesCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link Array.<module:model/Game>}
     */
    this.getCurrentGames = function(callback) {
      var postBody = null;


      var pathParams = {
      };
      var queryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = [];
      var contentTypes = [];
      var accepts = ['application/json'];
      var returnType = [Game];

      return this.apiClient.callApi(
        '/games/current', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }
  };

  return exports;
}));
